### ISSUE TITLE
Bootstrap Error

### ISSUE THREAD

**Issue by Speik** [ruViolence/GraalJS-Expansion#1]
Hello. Using Minecraft core Purpur 1.18.2

### GraalVM installed on machine, JAVA_HOME and PATH is updated, so `java -version` is:

```log
openjdk version "17.0.4" 2022-07-19
OpenJDK Runtime Environment GraalVM CE 22.2.0 (build 17.0.4+8-jvmci-22.2-b06)
OpenJDK 64-Bit Server VM GraalVM CE 22.2.0 (build 17.0.4+8-jvmci-22.2-b06, mixed mode, sharing)
```

### Server started correctly, but PAPI throws an error on GraalJS Expansion initialisation:

```log
[00:31:28] [Server thread/ERROR]: [PlaceholderAPI] Failed to load expansion class GraalJSExpansion (Is a dependency missing?)
[00:31:28] [Server thread/ERROR]: [PlaceholderAPI]
java.lang.NoClassDefFoundError: org/graalvm/polyglot/Context
	at ru.violence.papi.expansion.graaljs.evaluator.EvaluatorFactory.create(EvaluatorFactory.java:22) ~[?:?]
	at ru.violence.papi.expansion.graaljs.script.JavascriptPlaceholder.<init>(JavascriptPlaceholder.java:13) ~[?:?]
	at ru.violence.papi.expansion.graaljs.GraalJSExpansion.register(GraalJSExpansion.java:79) ~[?:?]
	at me.clip.placeholderapi.expansion.manager.LocalExpansionManager.register(LocalExpansionManager.java:172) ~[PlaceholderAPI-2.11.1.jar:?]
	at me.clip.placeholderapi.commands.impl.local.CommandExpansionRegister.lambda$evaluate$0(CommandExpansionRegister.java:79) ~[PlaceholderAPI-2.11.1.jar:?]
	at me.clip.placeholderapi.util.Futures.lambda$onMainThread$0(Futures.java:46) ~[PlaceholderAPI-2.11.1.jar:?]
	at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.18.2.jar:git-Purpur-1632]
	at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[purpur-1.18.2.jar:git-Purpur-1632]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1559) ~[purpur-1.18.2.jar:git-Purpur-1632]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:522) ~[purpur-1.18.2.jar:git-Purpur-1632]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1483) ~[purpur-1.18.2.jar:git-Purpur-1632]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1247) ~[purpur-1.18.2.jar:git-Purpur-1632]
	at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:321) ~[purpur-1.18.2.jar:git-Purpur-1632]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ClassNotFoundException: org.graalvm.polyglot.Context
	at java.net.URLClassLoader.findClass(URLClassLoader.java:445) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:587) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	... 14 more
```

### Tried to start server using `<path/to/graalvm>/bin/java` directly, but just got

```log
[PlaceholderAPI] [graaljs] This server is not running on GraalVM!
```

**Comment by ruViolence** [comment]
Hmm. Just tested on `purpur-1.18.2-1632` and the expansion loaded successfully. What version of `GraalJS Expansion` are you using?

**Comment by Speik** [comment]
Thank you for your answer. I'm using apparently latest version of GraalJS Expansion, it's fresh downloaded from eCloud.

Purpur version `1632`
PAPI version `2.11.1`
GraalJS Expansion version `1.1.1`

**Comment by ruViolence** [comment]
All right. I figured out what the problem was. Try the new version of the expansion [1.1.2](https://github.com/ruViolence/GraalJS-Expansion/releases/tag/v1.1.2). Also you probably need to install the JavaScript language in GraalVM as described [here](https://www.graalvm.org/22.2/reference-manual/graalvm-updater/#install-components-on-graalvm-community).

**Comment by Speik** [comment]
Finally I've found time to test - and it works! Much thanks, for me as for JS developer your expansion is totally necessary!
