### ISSUE TITLE
This extension will become unavailable when working on GraalVm since Java 21

### ISSUE THREAD

**Issue by heyhey123-git** [ruViolence/GraalJS-Expansion#3]
### What's my problem?
Following the prompts, I downloaded GraalVm for Java 21.x from the GraalVm official site (that you told us it was available in the read.me file). However, an error is thrown when loading this extension telling me that the extension is not being run on GraalVm. Using Java 20 or earlier does not throw this error; instead, the extension will work properly. And, the error is completely inconsistent with the error reported for uninstalled languages. And it's not possible to install the language on Java 21+, because GraalVm has deprecated the framework (see here: [issue about `gu` being deprecated](https://github.com/graalvm/container/issues/88); [the graaljs repository's description of how to install GraalVM JavaScript](https://github.com/oracle/graaljs)).

### How to reproduce the bug?
In my testing, running this extension on GraalVm for both Java 21.x and Java 22.x triggers this issue.

### How might the issue be resolved?
Based on the error message, it seems that this extension needs an update to replace the old external library. Also, you need to embed graaljs as a dependency. I tried to do this myself and recompile, but it failed due to some conflict.

### Full error message
```
[23:52:33] [Region Scheduler Thread #0/ERROR]: [PlaceholderAPI] [graaljs] This server is not running on GraalVM!
java.lang.ClassNotFoundException: org.graalvm.polyglot.Context
	at java.net.URLClassLoader.findClass(URLClassLoader.java:445) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:593) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Class.java:421) ~[?:?]
	at java.lang.Class.forName(Class.java:412) ~[?:?]
	at ru.violence.papi.expansion.graaljs.evaluator.EvaluatorFactory.create(EvaluatorFactory.java:19) ~[?:?]
	at ru.violence.papi.expansion.graaljs.script.JavascriptPlaceholder.<init>(JavascriptPlaceholder.java:13) ~[?:?]
	at ru.violence.papi.expansion.graaljs.GraalJSExpansion.register(GraalJSExpansion.java:76) ~[?:?]
	at me.clip.placeholderapi.expansion.manager.LocalExpansionManager.register(LocalExpansionManager.java:193) ~[PlaceholderAPI-2.11.6.jar:?]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[?:?]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1708) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682) ~[?:?]
	at me.clip.placeholderapi.expansion.manager.LocalExpansionManager.lambda$registerAll$4(LocalExpansionManager.java:366) ~[PlaceholderAPI-2.11.6.jar:?]
	at me.clip.placeholderapi.util.Futures.lambda$null$0(Futures.java:46) ~[PlaceholderAPI-2.11.6.jar:?]
	at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[lightingluminol-1.20.4.jar:git-Luminol-"ff65dc2"]
	at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[lightingluminol-1.20.4.jar:git-Luminol-"ff65dc2"]
	at io.papermc.paper.threadedregions.RegionizedServer.globalTick(RegionizedServer.java:298) ~[lightingluminol-1.20.4.jar:git-Luminol-"ff65dc2"]
	at io.papermc.paper.threadedregions.RegionizedServer$GlobalTickTickHandle.tickRegion(RegionizedServer.java:149) ~[lightingluminol-1.20.4.jar:git-Luminol-"ff65dc2"]
	at io.papermc.paper.threadedregions.TickRegionScheduler$RegionScheduleHandle.runTick(TickRegionScheduler.java:404) ~[lightingluminol-1.20.4.jar:git-Luminol-"ff65dc2"]
	at ca.spottedleaf.concurrentutil.scheduler.SchedulerThreadPool$TickThreadRunner.run(SchedulerThreadPool.java:525) ~[lightingluminol-1.20.4.jar:git-Luminol-"ff65dc2"]
	at java.lang.Thread.run(Thread.java:1583) ~[?:?]
``` 

### Expected results
Enables this plugin to work properly on GraalVm for Java 21 +.

**Comment by ruViolence** [comment]
This is a known issue. It mostly occurs due to the limitations of the PlaceholderAPI class loader. I plan to rewrite this project as a standalone plugin in the near future. Since I'm still using Java 17, it might take some time before I can get to it. Sorry for the inconvenience.

**Comment by heyhey123-git** [comment]
This issue seems to have been fixed in the latest release of GraalVm (the version that I've tested to work properly with this extension: GraalVM for JDK 22 Community 22.0.2).
